
services:

  db:
# https://github.com/MariaDB/mariadb-docker
# https://hub.docker.com/_/mariadb/
    image: docker.io/library/mariadb:10.7
    restart: unless-stopped
    env_file: .env
#    environment:
#      - MYSQL_DATABASE=wordpress
    volumes:
      - ./mariadb-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
# https://github.com/docker-library/wordpress
# https://hub.docker.com/_/wordpress
    depends_on: [ "db" ]
    image: docker.io/library/wordpress:6.1-fpm-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MARIADB_USER}
      - WORDPRESS_DB_PASSWORD=${MARIADB_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./wordpress-www:/var/www/html

  webserver:
    depends_on:
      - wordpress
    image: docker.io/library/nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - ./wordpress-www:/var/www/html:ro
      - ./certbot-www:/var/www/certbot:ro
      - ./certbot-etc:/etc/letsencrypt:ro

  certbot:
# https://eff-certbot.readthedocs.io/en/stable/install.html#running-with-docker
# https://hub.docker.com/r/certbot/certbot
    depends_on: [ "webserver" ]
    image: docker.oi/certbot/certbot:latest
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-varlib:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email webmaster@your_domain --agree-tos --no-eff-email --staging -d your_domain -d www.your_domain
