version: "2.4"
services:

  db:
# https://github.com/MariaDB/mariadb-docker
# https://hub.docker.com/_/mariadb/
    image: docker.io/library/mariadb:10.7
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./mariadb-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      start_period: "60"

  wordpress:
# https://github.com/docker-library/wordpress
# https://hub.docker.com/_/wordpress
    depends_on: [ "db" ]
    image: docker.io/library/wordpress:6.1-fpm-alpine
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306 # db is the DB service name (above)
      - WORDPRESS_DB_USER=${MARIADB_USER}
      - WORDPRESS_DB_PASSWORD=${MARIADB_PASSWORD}
      - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
    volumes:
      - ./wordpress-www:/var/www/html

  webserver:
# https://github.com/nginxinc/docker-nginx
# https://hub.docker.com/_/nginx
    depends_on:
      - wordpress
    image: docker.io/library/nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:8080"  # you should use 80 to make certbot working
      - "${HTTPS_PORT}:8443" # we use internal ports below 80
    environment: # nginx.conf template environment
      - NGINX_HTTP_PORT=8080      # server: listen
      - NGINX_HTTPS_PORT=8443     # server: listen
      - DOMAIN_NAME=${NGINX_SERVER_NAME_PRIMARY}                 # server: server_name (main)
      - DOMAIN_NAME_ALIASES=${NGINX_SERVER_NAME_ALIASES} # server: server_name (list)
    volumes:
      - ./nginx-templates:/etc/nginx/templates:ro
      - ./nginx-templates/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf:ro
      - ./wordpress-www:/var/www/html:ro  # according with wordpress.conf.template
      - ./certbot-www:/var/www/certbot:ro # according with wordpress.conf.template
      - ./certbot-etc:/etc/letsencrypt:ro # according with wordpress.conf.template
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "--show-error", "http://localhost:8080" ]
      start_period: "60"

  certbot:
# https://eff-certbot.readthedocs.io/en/stable/install.html#running-with-docker
# https://hub.docker.com/r/certbot/certbot
    depends_on: [ "webserver" ]
    image: docker.io/certbot/certbot:latest
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-www:/var/www/certbot
    command: certonly --webroot --agree-tos --webroot-path=/var/www/certbot --no-eff-email ${CERTBOT_COMMANDLINE}
