version: "2.4" # 3.x is not needed

services:

  db: &db # https://github.com/MariaDB/mariadb-docker
    image: docker.io/library/mariadb:${MARIADB_TAG:-10.7}
    restart: unless-stopped
    environment: # you can comment this section after db initialisation complete
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test: mariadb --user=${MARIADB_USER} --password=${MARIADB_PASSWORD} -e "select 1;"

  wordpress: &wordpress # https://github.com/docker-library/wordpress
    depends_on: [ "db" ]
    image: docker.io/library/wordpress:${WORDPRESS_TAG:-6.1-fpm-alpine}
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306 # db is the DB service name (above)
      - WORDPRESS_DB_USER=${MARIADB_USER}
      - WORDPRESS_DB_PASSWORD=${MARIADB_PASSWORD}
      - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
    volumes:
      - ./wordpress:/var/www/html
    healthcheck:
      test: ps -T

  webserver: # https://github.com/nginxinc/docker-nginx
    depends_on:
      - wordpress
    image: docker.io/library/nginx:${NGINX_TAG:-stable-alpine}
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:8080"   # default HTTP_PORT=80 to make certbot working
      - "${HTTPS_PORT:-443}:8443" # internal ports are equal to the templates
    environment: # nginx.conf template environment
      - SERVER_NAME=${NGINX_SERVER_NAME} ${NGINX_SERVER_NAMES} # server: server_name (list)
      - CERTBOT_ARCHIVE=${NGINX_SERVER_NAME} # ssl-secrets location part
    volumes:
      - ./wordpress:/var/www/html:ro     # main site dir
      - ${NGINX_TEMPLATE:-./nginx/http.conf.template}:/etc/nginx/templates/default.conf.template:ro
      - ${NGINX_SSLCONF_CERTOBOT:-./nginx/options-ssl-nginx.conf}:/etc/nginx/options-ssl-nginx.include:ro
      - ./certbot:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro
      - phpmyadmin:/var/www/phpmyadmin:ro
    healthcheck:
      test: curl http://localhost:8080/.healthcheck
    logging: # log files are in: journalctl CONTAINER_NAME=infra-wordpress_webserver_1
      driver: journald

  certbot: # https://eff-certbot.readthedocs.io/en/stable/install.html#running-with-docker
    depends_on: [ "webserver" ]
    image: docker.io/certbot/certbot:${CERTBOT_TAG:-latest}
    volumes:
      - ./certbot:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: ${CERTBOT_COMMAND:-renew}

volumes:
  certbot-www: # acme-challenge webdir
  phpmyadmin:  # phpmyadmin data dir
