version: "2.4" # 3.x is not needed
services:

  db: # https://github.com/MariaDB/mariadb-docker
    image: docker.io/library/mariadb:10.7
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./mariadb-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      start_period: "60"

  wordpress: # https://github.com/docker-library/wordpress
    depends_on: [ "db" ]
    image: docker.io/library/wordpress:6.1-fpm-alpine
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306 # db is the DB service name (above)
      - WORDPRESS_DB_USER=${MARIADB_USER}
      - WORDPRESS_DB_PASSWORD=${MARIADB_PASSWORD}
      - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
    volumes:
      - ./wordpress-www:/var/www/html

  webserver: # https://github.com/nginxinc/docker-nginx
    depends_on:
      - wordpress
    image: docker.io/library/nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:8080"   # default HTTP_PORT=80 to make certbot working
      - "${HTTPS_PORT:-443}:8443" # internal ports are equal to the templates
    environment: # nginx.conf template environment
      - SERVER_NAME=${NGINX_SERVER_NAME} ${NGINX_SERVER_NAMES} # server: server_name (list)
      - CERTBOT_ARCHIVE=${NGINX_SERVER_NAME} # ssl-secrets location part
    volumes:
      - ./wordpress-www:/var/www/html:ro     # main site dir
      - ${NGINX_TEMPLATE:-./nginx-etc/http.conf.template}:/etc/nginx/templates/default.template:ro
      - ${NGINX_SSLCONF_CERTOBOT:-./nginx-etc/options-ssl-nginx.conf}:/etc/nginx/templates/options-ssl-nginx.include:ro
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "--show-error", "http://localhost:8080" ]
      start_period: "60"

  certbot: # https://eff-certbot.readthedocs.io/en/stable/install.html#running-with-docker
    depends_on: [ "webserver" ]
    image: docker.io/certbot/certbot:latest
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: certonly --webroot --agree-tos --webroot-path=/var/www/certbot --no-eff-email ${CERTBOT_COMMANDLINE:--d ${NGINX_SERVER_NAME}}

volumes:
  certbot-etc: # certbot_archive
  certbot-www: # acme-challenge webroot
